# Generated by Django 6.0.4 on 2026-05-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_movimentacaoestoque_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('UN', 'UN - Unidade'), ('KG', 'KG - Quilograma'), ('G', 'G - Grama')], default='UN', max_length=2),
        ),
    ]
