# Generated by Django 6.0.4 on 2026-05-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_produto_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('UN', 'UN - Unidade'), ('KG', 'KG - Quilograma')], default='UN', max_length=2),
        ),
    ]
