# Generated by Django 6.0.4 on 2026-05-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produto_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codigo',
        ),
    ]
