# Generated by Django 6.0.4 on 2026-05-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pagamentos_recebimentos_status'),
        ('estoque', '0005_remove_produto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='movimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.movimentacaoestoque'),
        ),
    ]
